courier_site_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home,custom_admin_logout

urlpatterns = [
    path('',home, name="home"),
    path('secure-admin-panel/', admin.site.urls, name='admin'),
    path("admin/logout/", custom_admin_logout, name="admin-logout"),
    path('users/', include("users.urls")),
    path('shipments/', include("shipments.urls")),
    path("delivery/", include("delivery.urls")),
    path("notifications/", include("notifications.urls")),
    path("payments/", include("payments.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/urls.py
from django.urls import path
from .views import CourierApplicationView, CourierListView, SuccessView, accept_delivery_view, delivered_delivery_view

app_name = "delivery"  # app name

# list of urls
urlpatterns = [
    path("", CourierApplicationView.as_view(), name="create"),  # url for courier application page
    path("list/", CourierListView.as_view(), name='list'),  # url for list of assinged deliveries for courier
    path("success/", SuccessView.as_view(), name="success"),  # url for success page on successful application
    path("<int:id>/accept", accept_delivery_view, name='accept'),  # url for accepting assigned delivery
    path("<int:id>/delivered/", delivered_delivery_view, name="delivered")  # url fo r delivering assigned delivery
]

notifications/urls.py
from django.urls import path
from .views import *

app_name = "notifications"  # app name

# list of urls
urlpatterns = [
    path("", NotificationListView.as_view(), name="list"),  # notification list page
    path("mark-read/<int:pk>/", mark_as_read, name="mark_as_read"),  # mark as read url for appropriate view
    path("mark-all-read", mark_all_read, name="mark_all_read"),  # url for bulk(mark as read)
    path("delete/<int:pk>/", delete_notification, name="delete"),  # url for delete view
    path("delete_all", delete_all_notifications, name="delete_all")  # url for bulk delete of notifications
]

shipments/urls.py
from django.urls import path
from .views import *

app_name = "shipments"  # app name for urls

# list of urls for shipments app
urlpatterns = [
    path("", ShipmentCreateView.as_view(), name="create"),  # create shipment url
    path("list/", ShipmentListView.as_view(), name="list"),  # list of shipments page url
    path("<int:pk>", ShipmentDetailView.as_view(), name="detail"),  # detail of shipment page url
    path("<int:pk>/update/", ShipmentUpdateView.as_view(), name="update"),  # update shipment page url
    path("delete/", ShipmentDeleteView.as_view(), name="delete"),  # delete shipment url
    path("track/", track_shipment_view, name="track")  # track shipment page url

]

users/urls.py
from django.urls import path
from . import views

app_name = "users"  # name for indexing urls when loading url

# list of urls for the user app specified in the urlpatterns list.
urlpatterns = [
    path("", views.RegisterView.as_view(), name="register"),  # register page url
    path("login/", views.LoginView.as_view(), name="login"),  # login page url
    path("logout/", views.LogoutView.as_view(), name="logout"),  # logout url
    path("profile/", views.ProfileView.as_view(), name="profile"),  # profile page url
    path('lockout/', views.AxesLockoutView.as_view(), name='lockout')
]

templates/includes/_about.html
{% load static %}
<!-- ============================================-->
<!-- <section> begin ============================-->
<section class="pt-7 pb-0">

    <div class="container">
        <div class="row">
            <div class="col-6 col-lg mb-5">
                <div class="text-center"><img src="{% static 'img/icons/awards.png' %}" alt="..."/>
                    <h1 class="text-primary mt-4">26+</h1>
                    <h5 class="text-800">Awards won</h5>
                </div>
            </div>
            <div class="col-6 col-lg mb-5">
                <div class="text-center"><img src="{% static 'img/icons/states.png' %}" alt="..."/>
                    <h1 class="text-primary mt-4">65+</h1>
                    <h5 class="text-800">States covered</h5>
                </div>
            </div>
            <div class="col-6 col-lg mb-5">
                <div class="text-center"><img src="{% static 'img/icons/clients.png' %}" alt="..."/>
                    <h1 class="text-primary mt-4">689K+</h1>
                    <h5 class="text-800">Happy clients</h5>
                </div>
            </div>
            <div class="col-6 col-lg mb-5">
                <div class="text-center"><img src="{% static 'img/icons/goods.png' %}" alt="..."/>
                    <h1 class="text-primary mt-4">130M+</h1>
                    <h5 class="text-800">Goods delivered</h5>
                </div>
            </div>
            <div class="col-6 col-lg mb-5">
                <div class="text-center"><img src="{% static 'img/icons/business.png' %}" alt="..."/>
                    <h1 class="text-primary mt-4">130M+</h1>
                    <h5 class="text-800">Business hours</h5>
                </div>
            </div>
        </div>
    </div>
    <!-- end of .container-->

</section>
<!-- <section> close ============================-->
<!-- ============================================-->

templates/includes/_ads.html
{% load static %}
<!-- ============================================-->
<!-- <section> begin ============================-->
<section>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card bg-dark text-white py-4 py-sm-0"><img class="w-100"
                                                                       src="{% static 'img/gallery/video.png' %}"
                                                                       alt="video"/>
                    <div class="card-img-overlay bg-dark-gradient d-flex flex-column flex-center"><img
                            src="{% static 'img/icons/play.png' %}" width="80" alt="play"/>
                        <h5 class="text-primary">FASTEST DELIVERY</h5>
                        <p class="text-center">You can get your valuable item in the fastest period of<br
                                class="d-none d-sm-block"/>time with safety. Because your emergency<br
                                class="d-none d-sm-block"/>is our first priority.</p><a class="stretched-link" href="#"
                                                                                        data-bs-toggle="modal"
                                                                                        data-bs-target="#exampleModal"></a>
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                             aria-hidden="true">
                            <div class="modal-dialog modal-lg modal-dialog-centered">
                                <div class="modal-content overflow-hidden">
                                    <div class="modal-header p-0">
                                        <div class="ratio ratio-16x9" id="exampleModalLabel">
                                            <iframe src="https://www.youtube.com/embed/TlcP2aTOp-Q"
                                                    title="YouTube video" allowfullscreen="allowfullscreen"></iframe>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button class="btn btn-primary" type="button" data-bs-dismiss="modal">Close
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end of .container-->

</section>
<!-- <section> close ============================-->
<!-- ============================================-->

templates/includes/_contact.html
{% load static %}
<!-- ============================================-->
<!-- <section> begin ============================-->
<section>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-5 col-xl-4"><img src="{% static 'img/illustrations/callback.png' %}" alt="..."/>
                <h5 class="text-danger">REQUEST A CALLBACK</h5>
                <h2>We will contact in the shortest time.</h2>
                <p class="text-muted">Monday to Friday, 9am-5pm.</p>
            </div>
            <div class="col-md-6 col-lg-5 col-xl-4">
                <form class="row">
                    <div class="mb-3">
                        <label class="form-label visually-hidden" for="inputName">Name</label>
                        <input class="form-control form-quriar-control" id="inputName" type="text" placeholder="Name"/>
                    </div>
                    <div class="mb-3">
                        <label class="form-label visually-hidden" for="inputEmail">Another label</label>
                        <input class="form-control form-quriar-control" id="inputEmail" type="email"
                               placeholder="Email"/>
                    </div>
                    <div class="mb-5">
                        <label class="form-label visually-hidden" for="validationTextarea">Message</label>
                        <textarea class="form-control form-quriar-control is-invalid border-400" id="validationTextarea"
                                  placeholder="Message" style="height: 150px" required="required"></textarea>
                    </div>
                    <div class="d-grid">
                        <button class="btn btn-primary" type="submit">Send Message<i
                                class="fas fa-paper-plane ms-2"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- end of .container-->

</section>
<!-- <section> close ============================-->
<!-- ============================================-->

templates/includes/_find_us.html
{% load static %}
<!-- ============================================-->
<!-- <section> begin ============================-->
<section id="findUs">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-5 mb-6 text-center">
                <h5 class="text-danger">FIND US</h5>
                <h2>Access us easily</h2>
            </div>
            <div class="col-12">
                <div class="card card-span rounded-2 mb-3">
                    <div class="row">
                        <div class="col-md-6 col-lg-7 d-flex"><img
                                class="w-100 fit-cover rounded-md-start rounded-top rounded-md-top-0"
                                src="{% static 'img/gallery/map.svg' %}" alt="map"/></div>
                        <div class="col-md-6 col-lg-5 d-flex flex-center">
                            <div class="card-body">
                                <h5>Contact with us</h5>
                                <p class="text-700 my-4"><i class="fas fa-map-marker-alt text-warning me-3"></i><span>2277 Lorem Ave, San Diego, CA 22553</span>
                                </p>
                                <p><i class="fas fa-phone-alt text-warning me-3"></i><span class="text-700">Monday - Friday: 10 am - 10pm<br/><span
                                        class="ps-4">Sunday: 11 am - 9pm  </span></span></p>
                                <p><i class="fas fa-envelope text-warning me-3"> </i><a class="text-700"
                                                                                        href="mailto:vctung@outlook.com">
                                    info@quriarbox.com</a></p>
                                <ul class="list-unstyled list-inline mt-5">
                                    <li class="list-inline-item"><a class="text-decoration-none" href="#!"><i
                                            class="fab fa-facebook-square fs-2"></i></a></li>
                                    <li class="list-inline-item"><a class="text-decoration-none" href="#!"><i
                                            class="fab fa-instagram-square fs-2"></i></a></li>
                                    <li class="list-inline-item"><a class="text-decoration-none" href="#!"><i
                                            class="fab fa-twitter-square fs-2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-center">
                    <button class="btn btn-primary px-5" type="submit"><i class="fas fa-phone-alt me-2"></i><a
                            class="text-light" href="tel:123-456789">Call us to delivery 123-456789</a></button>
                </div>
            </div>
        </div>
    </div>
    <!-- end of .container-->

</section>
<!-- <section> close ============================-->
<!-- ============================================-->

templates/includes/_footer.html
{% load static %}
<!-- ============================================-->
<!-- <section> begin ============================-->
<section class="py-0 bg-1000">

    <div class="container">
        <div class="row justify-content-md-between justify-content-evenly py-4">
            <div class="col-12 col-sm-8 col-md-6 col-lg-auto text-center text-md-start">
                <p class="fs--1 my-2 fw-bold text-200">All rights Reserved &copy; Your Company, 2021</p>
            </div>
            <div class="col-12 col-sm-8 col-md-6">
                <p class="fs--1 my-2 text-center text-md-end text-200"> Made with&nbsp;
                    <svg class="bi bi-suit-heart-fill" xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                         fill="#F95C19" viewBox="0 0 16 16">
                        <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"></path>
                    </svg>&nbsp;by&nbsp;<a class="fw-bold text-primary" href="https://themewagon.com/" target="_blank">ThemeWagon </a>
                </p>
            </div>
        </div>
    </div>
    <!-- end of .container-->

</section>
<!-- <section> close ============================-->
<!-- ============================================-->


</main>
<!-- ===============================================-->
<!--    End of Main Content-->
<!-- ===============================================-->


<!-- ===============================================-->
<!--    JavaScripts-->
<!-- ===============================================-->
<script src="{% static 'vendors/@popperjs/popper.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'vendors/is/is.min.js' %}%"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
<script src="{% static 'vendors/fontawesome/all.min.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>

<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500;600;700;800&amp;display=swap"
      rel="stylesheet">
</body>

</html>

templates/includes/_header.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- ===============================================-->
    <!--    Document Title-->
    <!-- ===============================================-->
    <title>{% block title%} Home | courier app {% endblock %}</title>


    <!-- ===============================================-->
    <!--    Favicons-->
    <!-- ===============================================-->

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicons/favicon-16x16.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicons/favicon.ico' %}">
    <link rel="manifest" href="{% static 'img/favicons/manifest.json' %}">
    <meta name="msapplication-TileImage" content="{% static 'img/favicons/mstile-150x150.png' %}">
    <meta name="theme-color" content="#ffffff">


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet"/>

</head>
<body>

templates/includes/_home.html
{% load static %}
<section class="py-xxl-10 pb-0" id="home">
    <div class="bg-holder bg-size"
         style="background-image:url({% static 'img/gallery/hero-header-bg.png' %});
              background-position:top center;
              background-size:cover;">
    </div>
    <!--/.bg-holder-->

    <div class="container">
        <div class="row align-items-center">

            <!-- IMAGE COLUMN (mobile: first, desktop: right) -->
            <div class="col-md-5 col-xl-6 col-xxl-7 order-0 order-md-1 text-center text-md-end">
                <img class="pt-7 pt-md-0 w-100" src="{% static 'img/illustrations/hero.png' %}" alt="hero-header"/>
            </div>

            <!-- INFO COLUMN (mobile: second, desktop: left) -->
            <div class="col-md-7 col-xl-6 col-xxl-5 order-1 order-md-0 text-center text-md-start py-4">
                <h1 class="fw-normal fs-6 fs-xxl-7">A trusted provider of </h1>
                <h1 class="fw-bolder fs-6 fs-xxl-7 mb-2">courier services.</h1>

                <p class="fs-1 mb-5">
                    We deliver your products safely to
                    <br/>
                    your home in a reasonable time.
                </p>

                {% if not request.user.is_authenticated %}
                <a class="btn btn-primary me-2" href="{% url 'users:register' %}" role="button">
                    Get started<i class="fas fa-arrow-right ms-2"></i>
                </a>
                {% endif %}

                {% if request.user.profile.role == "customer" %}
                <a class="btn btn-primary me-2" href="{% url 'shipments:create' %}" role="button">
                    Create Shipment <i class="fas fa-arrow-right ms-2"></i>
                </a>

                <a class="btn btn-primary me-2" href="{% url 'delivery:create' %}" role="button">
                    Become a Courier<i class="fas fa-arrow-right ms-2"></i>
                </a>
                {% endif %}
            </div>

        </div>
    </div>
</section>

templates/includes/_link_section.html
{% load static %}
<!-- ============================================-->
<!-- <section> begin ============================-->
<section class="bg-900 pb-0 pt-5">

    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-lg-6 mb-4 order-0 order-sm-0"><a class="text-decoration-none" href="#"><img
                    src="{% static 'img/gallery/footer-logo.png' %}" height="51" alt=""/></a>
                <p class="text-500 my-4">The most trusted Courier<br/>company in your area.</p>
            </div>
            <div class="col-6 col-sm-4 col-lg-2 mb-3 order-2 order-sm-1">
                <h5 class="lh-lg fw-bold mb-4 text-light font-sans-serif">Other links </h5>
                <ul class="list-unstyled mb-md-4 mb-lg-0">
                    <li class="lh-lg"><a class="text-500" href="#!">Blogs</a></li>
                    <li class="lh-lg"><a class="text-500" href="#!">Movers website</a></li>
                    <li class="lh-lg"><a class="text-500" href="#!">Traffic Update</a></li>
                </ul>
            </div>
            <div class="col-6 col-sm-4 col-lg-2 mb-3 order-3 order-sm-2">
                <h5 class="lh-lg fw-bold text-light mb-4 font-sans-serif">Services</h5>
                <ul class="list-unstyled mb-md-4 mb-lg-0">
                    <li class="lh-lg"><a class="text-500" href="#!">Corporate goods</a></li>
                    <li class="lh-lg"><a class="text-500" href="#!">Artworks</a></li>
                    <li class="lh-lg"><a class="text-500" href="#!">Documents</a></li>
                </ul>
            </div>
            <div class="col-6 col-sm-4 col-lg-2 mb-3 order-3 order-sm-2">
                <h5 class="lh-lg fw-bold text-light mb-4 font-sans-serif"> Customer Care</h5>
                <ul class="list-unstyled mb-md-4 mb-lg-0">
                    <li class="lh-lg"><a class="text-500" href="#!">About Us</a></li>
                    <li class="lh-lg"><a class="text-500" href="#!">Contact US</a></li>
                    <li class="lh-lg"><a class="text-500" href="#!">Get Update</a></li>
                </ul>
            </div>
        </div>
    </div>
    <!-- end of .container-->

</section>
<!-- <section> close ============================-->
<!-- ============================================-->

templates/includes/_navbar.html
{% load static %}
<!-- ===============================================-->
<!--    Main Content-->
<!-- ===============================================-->
<main class="main" id="top">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3 d-block"
         data-navbar-on-scroll="data-navbar-on-scroll">


        <div class="container">
            {% if request.user.is_authenticated %}
            <span style="font-size:12px"> Welcome back <br/> {{ request.user.username }} </span>
            {% else %}
            <a class="navbar-brand" href="#"><img src="{% static 'img/gallery/logo.png' %}" height="45" alt="logo"/></a>
            {% endif %}


            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">


                <ul class="navbar-nav ms-auto pt-2 pt-lg-0 font-base">

                    <li class="nav-item px-2">
                        <a class="nav-link " aria-current="page" href="{% url 'home'%}">Home</a>
                    </li>

                    <li class="nav-item px-2">
                        <a class="nav-link " href="{% url 'shipments:track' %}">
                            Track shipment
                        </a>
                    </li>

                    <li class="nav-item px-2">
                        {% if request.user.is_authenticated %}
                        <a class="nav-link " href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                        {% endif %}
                    </li>

                </ul>


                <div class="dropdown d-none d-lg-block">

                    {% if shipments or assigned_deliveries %}
                    {% if request.user.profile.role == 'customer' %}
                    <!-- Search Button -->
                    <button class="btn bg-soft-warning ms-2" id="dropdownMenuButton1"
                            type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-search text-warning"></i>
                    </button>

                    <!-- Dropdown Search Box -->
                    <div class="dropdown-menu dropdown-menu-lg-end p-0 rounded"
                         aria-labelledby="dropdownMenuButton1" style="top:55px">
                        <form method="get" action="{% url 'shipments:list' %}">
                            <input class="form-control border-200" type="search"
                                   name="q" value="{{ request.GET.q|default:'' }}"
                                   placeholder="Search Shipments..."
                                   aria-label="Search"/>

                        </form>
                    </div>
                    {% elif request.user.profile.role == 'courier' %}
                    <!-- Search Button -->
                    <button class="btn bg-soft-warning ms-2" id="dropdownMenuButton1"
                            type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-search text-warning"></i>
                    </button>

                    <!-- Dropdown Search Box -->
                    <div class="dropdown-menu dropdown-menu-lg-end p-0 rounded"
                         aria-labelledby="dropdownMenuButton1" style="top:55px">
                        <form method="get" action="{% url 'delivery:list' %}">
                            <input class="form-control border-200" type="search"
                                   name="q" value="{{ request.GET.q|default:'' }}"
                                   placeholder="Search Shipments..."
                                   aria-label="Search"/>
                        </form>
                    </div>
                    {% endif %}
                    {% endif %}

                </div>

                {% if request.user.is_authenticated %}

                {% if request.user.profile.role == 'customer'%}
                <a class="btn btn-primary order-1 order-lg-0 ms-lg-3" href="{% url 'shipments:list' %}">Shipments</a>
                {% elif request.user.profile.role == "courier" %}
                <a class="btn btn-primary order-1 order-lg-0 ms-lg-3" href="{% url 'delivery:list' %}">Assigned
                    deliveries</a>
                {% elif request.user.profile.role == "admin" %}
                <a class="btn btn-primary order-1 order-lg-0 ms-lg-3" href="secure-admin-panel/">Admin panel</a>
                {% endif %}

                <a class="btn  ms-2" href="{% url 'users:profile' %}"><i class="fas fa-2x fa-user-circle "></i>
                </a>
                {% else %}
                <a class="btn btn-primary order-1 order-lg-0 ms-lg-3" href="{% url 'users:register' %}">Register</a>
                {% endif %}


                <!-- search bar that shows on mobile view of site -->
                {% if shipments or assigned_deliveries %}
                {% if request.user.profile.role == 'customer' %}
                <form class="d-flex my-3 d-block d-lg-none" method="get" action="{% url 'shipments:list' %}">
                    <input class="form-control me-2 border-200 bg-light"
                           name="q" value="{{ request.GET.q|default:'' }}"
                           type="search" placeholder="Search Shipments..." aria-label="Search"/>
                    <button class="btn btn-outline-primary" type="submit">Search</button>
                </form>

                {% elif request.user.profile.role == 'courier' %}
                <form class="d-flex my-3 d-block d-lg-none" method="get" action="{% url 'delivery:list' %}">
                    <input class="form-control me-2 border-200 bg-light"
                           name="q" value="{{ request.GET.q|default:'' }}"
                           type="search" placeholder="Search Shipments..." aria-label="Search"/>
                    <button class="btn btn-outline-primary" type="submit">Search</button>
                </form>
                {% endif %}
                {% endif %}


                {% comment %} Notification section {% endcomment %}
                <li class="nav-item dropdown list-unstyled">
                    <a class="btn" href="#" id="navbarDropdownNotifications" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-bell fa-1x"></i>
                        {% if unread_notification_count > 0 %}
                        <span class="text-primary position-absolute top-0 start-90 translate-middle">
                  {{ unread_notification_count }}
                 </span>
                        {% endif %}
                    </a>

                    <ul class="dropdown-menu dropdown-menu-end p-0 shadow list-unstyled"
                        aria-labelledby="navbarDropdownNotifications"
                        style="min-width: 300px;">
                        <li class="dropdown-header bg-soft-warning text-dark fw-bold px-3 py-2">
                            Notifications
                        </li>

                        {% if recent_notifications %}
                        {% for n in recent_notifications %}
                        <li>
                            <a href="{% url 'notifications:mark_as_read' n.id %}"
                               class="dropdown-item small {% if not n.is_read %}fw-bold{% endif %}">
                                {{ n.message|truncatechars:50 }}
                                <br>
                                <small class="text-muted">{{ n.created_at|timesince }} ago</small>
                            </a>
                        </li>
                        {% endfor %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item text-center text-primary fw-bold"
                               href="{% url 'notifications:list' %}">
                                View all notifications
                            </a>
                        </li>
                        {% else %}
                        <li>
                            <span class="dropdown-item text-muted">No notifications</span>
                        </li>
                        {% endif %}
                    </ul>
                </li>


            </div>
        </div>
    </nav>

templates/includes/_newsletter.html
{% load static %}
<!-- ============================================-->
<!-- <section> begin ============================-->
<section class="bg-1000">

    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h2 class="fw-bold text-white">Get an update every week</h2>
                <p class="text-300">We ensure that your product is delivered in the safest possible<br/>manner, at the
                    correct location, at the right time.</p>
            </div>
            <div class="col-lg-6">
                <h5 class="text-primary mb-3">SUBSCRIBE TO NEWSLETTER </h5>
                <form class="row gx-2 gy-2 align-items-center">
                    <div class="col">
                        <div class="input-group-icon">
                            <label class="visually-hidden" for="inputEmailCta">Address</label>
                            <input class="form-control input-box form-quriar-control text-light" id="inputEmailCta"
                                   type="email" placeholder="Enter your mail"/>
                        </div>
                    </div>
                    <div class="d-grid gap-3 col-sm-auto">
                        <button class="btn btn-danger" type="submit">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- end of .container-->

</section>
<!-- <section> close ============================-->
<!-- ============================================-->