courier_site_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home,custom_admin_logout

urlpatterns = [
    path('',home, name="home"),
    path('secure-admin-panel/', admin.site.urls, name='admin'),
    path("admin/logout/", custom_admin_logout, name="admin-logout"),
    path('users/', include("users.urls")),
    path('shipments/', include("shipments.urls")),
    path("delivery/", include("delivery.urls")),
    path("notifications/", include("notifications.urls")),
    path("payments/", include("payments.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/urls.py
from django.urls import path
from .views import CourierApplicationView, CourierListView, SuccessView, accept_delivery_view, delivered_delivery_view

app_name = "delivery"  # app name

# list of urls
urlpatterns = [
    path("", CourierApplicationView.as_view(), name="create"),  # url for courier application page
    path("list/", CourierListView.as_view(), name='list'),  # url for list of assinged deliveries for courier
    path("success/", SuccessView.as_view(), name="success"),  # url for success page on successful application
    path("<int:id>/accept", accept_delivery_view, name='accept'),  # url for accepting assigned delivery
    path("<int:id>/delivered/", delivered_delivery_view, name="delivered")  # url fo r delivering assigned delivery
]

payments/urls.py
from django.urls import path
from .views import *

app_name = "payments"  # app name

# list of urls
urlpatterns = [
    path("receipt/<int:shipment_id>", receipt_view, name="receipt"),  # url for receipt page
    path("receipt/download/<int:pk>", download_receipt_pdf, name="download-receipt"),  # url for downloading receipts
    path("initiate/<int:pk>", initiate_payment_view, name="initiate"),  # url for initiating payment on payment gateway
    path("verify/", verify_payment_view, name="verify"),  # url for verifying payment on payment gateway
    path("history/", PaymentHistoryView.as_view(), name="payments-history"),  # url for payment history page
    path("webhook/", flutterwave_webhook_view, name='webhook')  # url for webhook support
]

shipments/urls.py
from django.urls import path
from .views import *

app_name = "shipments"  # app name for urls

# list of urls for shipments app
urlpatterns = [
    path("", ShipmentCreateView.as_view(), name="create"),  # create shipment url
    path("list/", ShipmentListView.as_view(), name="list"),  # list of shipments page url
    path("<int:pk>", ShipmentDetailView.as_view(), name="detail"),  # detail of shipment page url
    path("<int:pk>/update/", ShipmentUpdateView.as_view(), name="update"),  # update shipment page url
    path("delete/", ShipmentDeleteView.as_view(), name="delete"),  # delete shipment url
    path("track/", track_shipment_view, name="track")  # track shipment page url

]

users/urls.py
from django.urls import path
from . import views

app_name = "users"  # name for indexing urls when loading url

# list of urls for the user app specified in the urlpatterns list.
urlpatterns = [
    path("", views.RegisterView.as_view(), name="register"),  # register page url
    path("login/", views.LoginView.as_view(), name="login"),  # login page url
    path("logout/", views.LogoutView.as_view(), name="logout"),  # logout url
    path("profile/", views.ProfileView.as_view(), name="profile"),  # profile page url
    path('lockout/', views.AxesLockoutView.as_view(), name='lockout')
]

shipments/models.py
"""
defining models for the shipments app to model entities to be stored in the database
"""

from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils import timezone


class Shipment(models.Model):
    """
    defining the Model for the Shipment entity
    """
    STATUS_CHOICES = [
        ("PENDING", "Pending"),
        ("IN_TRANSIT", "In Transit"),
        ("DELIVERED", "Delivered"),
        ("CANCELED", "Cancelled"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="shipments")  # user field related to the built in django's User model
    tracking_number = models.CharField(max_length=20, unique=True,
                                       blank=True)  # tracking id field to uniquely identify and track shipments
    origin_address = models.TextField(max_length=255)  # origin address field
    destination_address = models.TextField(max_length=255)  # destination address field
    weight = models.DecimalField(max_digits=6, decimal_places=2)  # shipments weight field
    cost = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)  # cost of shipment field
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="PENDING")  # shipments status field
    created_at = models.DateTimeField(auto_now_add=True)  # date created automatically filled on creation
    updated_at = models.DateTimeField(auto_now=True)  # date updated automatically filled on update

    def mark_delivered(self):
        """method to set status to delivered"""
        self.status = 'DELIVERED'
        self.updated_at = timezone.now()
        self.save(update_fields=['status', 'updated_at'])

    def mark_in_transit(self):
        """method to set status to in_transit"""
        self.status = 'IN_TRANSIT'
        self.save()

    def calc_cost(self):
        """method to calculate cost of shipment"""
        self.cost = float(self.weight) * 0.01

    def save(self, *args, **kwargs):
        """ 
        overriding save() method to auto generate unique tracking_numbers on saving instances of the shipment 
        """
        # generating tracking_number for shipment
        if not self.tracking_number:
            while True:
                code = str(uuid.uuid4())[:12].upper()  # generating unique tracking_id using uuid
                if not Shipment.objects.filter(tracking_number=code).exists():
                    self.tracking_number = code
                    break

        # calculation for cost of shipment
        self.calc_cost()  # sets cost for shipment
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.tracking_number} - {self.status}"

    def payment_status(self):
        """returns status of related payments field"""
        return self.payment.status

shipments/forms.py
from django import forms
from .models import Shipment


class ShipmentForm(forms.ModelForm):
    """
    defining a form for the create shipment page
    """

    class Meta:
        model = Shipment  # binds form to the Shipment model
        exclude = ['user', 'tracking_number', 'status', 'cost']  # excludes specified fields

shipments/views.py
"""
Defining views(processes requests and returns appropriate responses) for the shipments app
"""

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, View
from .forms import ShipmentForm
from .models import Shipment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models
from django.contrib import messages
from django.http import HttpResponseForbidden, HttpResponseNotFound
from delivery.models import DeliveryAssignment

class ShipmentCreateView(LoginRequiredMixin, CreateView):
    """
    defining view to process request for shipment creation page
    """
    model = Shipment  # binds view to model
    template_name = "shipments/create.html"  # template to render
    form_class = ShipmentForm  # binds form to this view
    success_url = reverse_lazy("shipments:list")  # redirects to shipment list page on successful creation of shipment
    login_url = "users:login"  # login page if not authenticated

    def form_valid(self, form):
        # assign logged-in user before saving
        form.instance.user = self.request.user
        messages.success(self.request, "Shipment created.")  # sends success message to displayed page
        return super().form_valid(form)


class ShipmentListView(LoginRequiredMixin, ListView):
    """
    processes request for the shipments list page 
    """
    model = Shipment  # binds model to this view
    template_name = "shipments/list.html"  # template to render
    context_object_name = "shipments"  # the context name referenced in the template
    login_url = "users:login"  # login page if not authenticated


    def get_queryset(self):
        """overrides method to process the object to be returned and referenced as the context_object in the template """
        user = self.request.user  # authenticated user
        query = self.request.GET.get("q")  # search parameter 'q' passed from the page to search through shipments
        status = self.request.GET.get("status")  # status parameter passed from the page to filter shipments

        qs = Shipment.objects.filter(user=user).order_by("-created_at")  # shipments for authenticated user

        if query:
            # filters shipments based on search  parameter 'query'
            qs = qs.filter(
                models.Q(tracking_number__icontains=query) |
                models.Q(origin_address__icontains=query) |
                models.Q(destination_address__icontains=query)
            )

        if status and status != "ALL":
            # filters shipments based on status parameter from the page
            qs = qs.filter(status=status)

        return qs

    def get_context_data(self, **kwargs):
        """
        process the context_data for the page 
        """
        context = super().get_context_data(**kwargs)
        context["status_choices"] = Shipment.STATUS_CHOICES  # context reference for status_choices on the model
        context["selected_status"] = self.request.GET.get("status", "ALL")  # context reference for selected_status
        context["query"] = self.request.GET.get("q", "")  # context reference for the passed search parameter 'query'
        return context


class ShipmentDetailView(LoginRequiredMixin, DetailView):
    """process request for a shipment detail page"""
    model = Shipment  # binds view to the Shipment model
    template_name = "shipments/detail.html"  # template to render
    context_object_name = "shipment"  # context reference for the Shipment instance
    login_url = "users:login"  # login page if not authenticated
 

    def get_queryset(self):
        """
        only user who own shipment see's details
        except they are couriers which can view detals just to accept
        shipment and mark as delivered
        """
        owned_shipments = Shipment.objects.filter(user=self.request.user)
        assigned_shipments = Shipment.objects.filter(deliveryassignment__courier__user=self.request.user)

        
        return owned_shipments or assigned_shipments

        
    


class ShipmentUpdateView(LoginRequiredMixin, UpdateView):
    """
    processes requests for the update shipment page
    """
    model = Shipment  # binds view to Shipment model
    template_name = "shipments/update.html"  # template to render
    form_class = ShipmentForm  # binds form to this view
    success_url = reverse_lazy("shipments:list")  # page to render on succesful update
    login_url = "users:login"  # login page if not authenticated

    def form_valid(self, form):
        """validates form"""
        messages.success(self.request,
                         f"Shipment {form.instance.tracking_number} updated.")  # sends success message on displayed page
        form.instance.calc_cost()
        return super().form_valid(form)
    
    def get_queryset(self):
        return Shipment.objects.filter(user=self.request.user) # filtering resultset so only owners update their shipments


class ShipmentDeleteView(LoginRequiredMixin, View):
    """processes the request for deleting shipments """
    login_url = 'users:login' # login page 

    def post(self, request, *args, **kwargs):
        """processes request for bulk delete"""
        shipment_ids = request.POST.getlist(
            "shipments")  # retrieves list of selected shipments on the shipment list page
        if shipment_ids:
            user_shipments = Shipment.objects.filter(id__in=shipment_ids,
                                    user=request.user)  # filters shipments for user
            if user_shipments :
                user_shipments.delete() # deletes shipments
                
                messages.warning(request, "shipments deleted.")  # sends message on displayed page
                return redirect("shipments:list")  # redirects to shipment list page
            else:
                return HttpResponseNotFound()# returns not allowed http status


def track_shipment_view(request):
    """ processes request to track shipment on the track shipment page """
    shipment = None
    error = None

    if request.method == "POST":
        tracking_number = request.POST.get(
            "tracking_number").strip()  # retrieves tracking_number passed to the view by the track shipment page
        try:
            shipment = Shipment.objects.get(
                tracking_number=tracking_number)  # gets the shipment based on tracking_number
        except Shipment.DoesNotExist:
            error = "No shipment found with that tracking number."  # error if shipment is not found
    return render(request, "shipments/track.html", {"shipment": shipment,
                                                    "error": error})  # renders template and passes the context dictionary accordingly

shipments/templates/shipments/create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<div class=' mt-7 mb-3 card p-2 w-md-50 shadow-sm' style="margin:auto">
    <form method="post" style="margin:auto;width:60%">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit" class="btn btn-primary col-md-5" style="margin-left:100px">
    </form>
</div>

<style>
    textarea{height:3rem;}
    input[type="number"]{height:2rem;max-width:6rem;}

</style>
{% endblock %}

shipments/templates/shipments/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-7 mb-3">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="card shadow-sm border-0 rounded-lg" style="font-family:arial;">
                <div class="card-header bg-primary text-white">
                    <h5 class="mb-0">Shipment #{{ shipment.tracking_number }}</h5>
                </div>
                <div class="card-body">

                    <div class="row mb-3">
                        <div class="col-4">
                            <h6 class="text-muted">Sender</h6>
                            <p>{{ shipment.user.username }}</p>
                        </div>
                        <div class="col-4">
                            <h6 class="text-muted">Pickup Address</h6>
                            <p>{{ shipment.origin_address }}</p>
                        </div>
                        <div class="col-4">
                            <h6 class="text-muted">Recipient Address</h6>
                            <p>{{ shipment.destination_address }}</p>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-4">
                            <h6 class="text-muted">Weight</h6>
                            <p>{{ shipment.weight }} kg</p>
                        </div>
                        <div class="col-4">
                            <h6 class="text-muted">Cost</h6>
                            <p>${{ shipment.cost }}</p>
                        </div>
                        <div class="col-4">
                            <h6 class="text-muted">Status</h6>
                            <span class="p-2 text-white {% if shipment.status == 'PENDING' %} bg-warning {% elif shipment.status == 'IN_TRANSIT' %} bg-info {% elif shipment.status == 'DELIVERED' %} bg-success {% endif %}">
                                {{ shipment.get_status_display }}
                            </span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 text-muted">
                            <small>Created: {{ shipment.created_at|date:"M d, Y H:i" }}</small>
                        </div>
                    </div>

                </div>

                {% if request.user.profile.role == 'customer' %}
                <div class="card-footer d-flex justify-content-between">
                    <a href="{% url 'shipments:list' %}" class=" btn btn-primary btn-sm ">← Back to Shipments</a>

                    {% if shipment.payment.status != 'PAID'%}
                    <a href="{% url 'payments:initiate' shipment.payment.pk %}"
                       class=" btn btn-info btn-sm text-white p-lg-2">
                        Pay Now
                    </a>
                    {% else %}
                    <a href="{% url 'payments:receipt' shipment.id %}" class="btn btn-sm  btn-success">View Receipt</a>
                    <a href="{% url 'payments:download-receipt' shipment.payment.receipt.pk %}"
                       class="btn btn-sm  btn-success"><i class="fas fa-file-pdf fa-1x"></i> Download Receipt(PDF)</a>
                    {% endif %}
                </div>
                {% elif request.user.profile.role == 'courier' %}
                <div class="card-footer d-flex justify-content-around">
                    <a href="{% url 'delivery:list' %}" class=" btn btn-primary btn-sm">← Back to Deliveries</a>

                    {% if shipment.status == 'IN_TRANSIT' %}
                    <a href="{% url 'delivery:delivered' shipment.id %}" class="btn btn-success btn-sm">Delivered
                        Shipment ✔</a>
                    {% elif shipment.status == 'PENDING' %}
                    <a href="{% url 'delivery:accept' shipment.id %}" class="btn btn-primary btn-sm">Accept Shipment</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock %}

shipments/templates/shipments/list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-7 mb-3 ">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <form method="get" class="d-flex align-items-center">
            <input type="hidden" name="q" value="{{ query }}">

            <select name="status" class="form-select form-select-sm me-2">
                <option value="ALL"
                 {% if selected_status == "ALL" %}
                 selected 
                 {% endif %} >All</option>
                {% for value, label in status_choices %}
                <option value="{{ value }}" 
                    {% if selected_status == value %}
                    selected
                    {% endif %} >{{ label }}</option>
                {% endfor %}
            </select>

            <button type="submit" class="btn btn-primary btn-sm">Filter</button>
        </form>

        <a class="btn btn-secondary" href="{% url 'payments:payments-history' %} " style="position:relative;top:55px">payment
            history</a>

    </div>

    <form method="post" action="{% url 'shipments:delete' %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary mb-2 " value="Delete selected"/>

        <table class="table table-responsive table-striped table-bordered bg-white ">
            <thead>
            <tr>
                <th>
                    <input type="checkbox" id="select_all">
                    Tracking ID
                </th>
                <th>Origin</th>
                <th>Destination</th>
                <th>Status</th>
                <th>Created</th>
            <tr>
            </thead>
            <tbody>
            {% for shipment in shipments %}
            <tr>

                <td>
                    <input type="checkbox" value="{{ shipment.id }}" name="shipments">
                    <a href="{% url 'shipments:detail' shipment.id %}" class="text-primary">{{ shipment.tracking_number}}</a></td>
                <td>{{ shipment.origin_address }}</td>
                <td>{{ shipment.destination_address }}</td>
                <td>{{ shipment.status }}</td>
                <td>{{ shipment.created_at|date:"Y-m-d H:i" }}</td>
                <td>{%if shipment.status != 'DELIVERED' %}
                    <a href="{% url 'shipments:update' shipment.id %}" class="text-primary">Update</a>
                    {% else %} <span class="text-success">Delivered</span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}

            {% if shipments|length == 0 %}
            <tr>
                <td colspan="8" class="text-center">
                    No Shipments Found
                    <a class="btn btn-primary p-1" href="{% url 'shipments:create' %}" role="button">
                        Create Shipment <i class="fas fa-arrow-right ms-2"></i>
                    </a>
                </td>
            </tr>

            {% endif %}

            </tbody>
        </table>
    </form>
</div>

<style>
    table{font-family:"fira code";font-size:14px}

</style>

<script>
document.getElementById("select_all").addEventListener("click", function(e) {
    let checkboxes = document.querySelectorAll('input[name="shipments"]');
    checkboxes.forEach(cb => cb.checked = e.target.checked);
});

</script>
{% endblock %}

shipments/templates/shipments/track.html
{% extends "base.html" %}

{% block content %}
<div class="container m-auto py-3 mt-7 w-md-50 ms-auto">

    <h2 class="mb-4">Track Your Shipment</h2>
    <form method="post" class="mb-4">
        {% csrf_token %}
        <div class="input-group">
            <input type="text" name="tracking_number" class="form-control" placeholder="Enter Tracking Number" required>
            <button class="btn btn-primary" type="submit">Track</button>
        </div>
    </form>

    {% if error %}
    <div class="alert alert-danger">{{ error }}</div>
    {% endif %}

    {% if shipment %}
    <div class="card shadow-sm p-3">
        <h5>Shipment: {{ shipment.tracking_number }}</h5>

        <!-- Progress bar -->
        <div class="progress mb-3" style="height: 30px;">
            <div class="progress-bar {% if shipment.status == 'PENDING' %}bg-success{% else %}bg-light text-dark{% endif %}"
                 style="width:33.3%">
                PENDING
            </div>
            <div class="progress-bar {% if shipment.status in 'IN_TRANSIT' %}bg-success{% else %}bg-light text-dark{% endif %}"
                 style="width:33.3%">
                IN TRANSIT
            </div>
            <div class="progress-bar {% if shipment.status == 'DELIVERED' %}bg-success{% else %}bg-light text-dark{% endif %}"
                 style="width:33.3%">
                DELIVERED
            </div>
        </div>

        <!-- Shipment details -->
        <p><strong>Status:</strong> {{ shipment.status }}</p>
        <p><strong>Origin:</strong> {{ shipment.origin_address }}</p>
        <p><strong>Destination:</strong> {{ shipment.destination_address }}</p>
        <p><strong>Weight:</strong> {{ shipment.weight }} kg</p>
        <p><strong>Created:</strong> {{ shipment.created_at|date:"M d, Y H:i" }}</p>
    </div>
    {% endif %}
</div>
{% endblock %}

shipments/templates/shipments/update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class=' mt-7 mb-3 card p-2 w-md-50 shadow-sm' style="margin:auto">
    <form method="post" style="margin:auto;width:60%">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Update" class="btn btn-primary col-md-5" style="margin-left:100px">
    </form>
</div>

<style>
    textarea{height:3rem;}
    input[type="number"]{height:2rem;max-width:6rem;}

</style>
{% endblock %}